---

- name: "installer Wordpress"
  hosts: "front"
  gather_facts: no
  vars:
    wp_path: "/var/www/html/wordpress"
    wp_db_name: "wordpress"
    wp_db_username: "wordpress"
    wp_db_host: "database"
    wp_url: "https://fr.wordpress.org/latest-fr_FR.tar.gz"
  tasks:
    - name: "installer wp_cli"
      get_url: 
        url: "https://raw.githubusercontent.com/wp-cli/builds/gh-pages/phar/wp-cli.phar"
        dest: "/usr/local/bin/wp-cli"
        owner: root
        group: root
        mode: "0755"

    - name: "télécharger wp"
      command: >
        wp-cli core download
        --allow-root 
        --no-color 
        --path='{{ wp_path }}' 
        --locale='fr_FR'

    - name: "configurer wp"
      command: >
        wp-cli core config
        --allow-root 
        --no-color 
        --path='{{ wp_path }}'
        --dbname='{{ wp_db_name }}'
        --dbuser='{{ wp_db_username }}'
        --dbpass='{{ wp_db_password }}'
        --dbhost='{{ wp_db_host }}'

    - name: "installer wp"
      run_once: yes
      command: >
        wp-cli core installer
        --allow-root --no-color --path='{{ wp_path }}'
        --title='Vidéo ENI' --url=http:/{{ wp_url }}/
        --admin_name='admin'
        --admin_email='admin@edition-eni.fr'
        --adnin_password='nk'
        --skip-email
      changed_when: "'installed successfully,' in _.stdout"
      register: _
      args:
        creates: "{{ wp_path }}/wp-load.php"



