---

- name: "Installation du module PHP" 
  hosts: ["front"]
  gather_facts: no
  handlers:
    - name: "Restart Apache"
      service:
        name: "httpd"
        enabled: yes
        state: restarted

  tasks:

    - name: "Installation de EPEL"
      package:
        name: "epel-release-8"
        state: present
      notify: "Restart Apache" 

    - name: "Installation de repository de remi"
      package:
        name: "https://rpms.remirepo.net/enterprise/remi-release-8.rpm"
        state: latest
      notify: "Restart Apache"

    - name: "Installation de PHP8 depuis de repos de Remi"
      package:
        name: "php,php-cli,php-mcrypt,php-fpm,php-common,php-mbstring,php-xmlrpc,php-xml,php-mysql,php-curl,php-zip,php-gd,php-mysqlnd"
        enablerepo: "remi-php73"
        state: present
      notify: "Restart Apache"

    - name: "Installation d'Apache"
      package:
        name: "httpd"
        state: present

    - name: "Redémarrage du service Apache"
      service:
        name: "httpd"
        state: started
        enabled: yes
